apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx-antiaffinity
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: serviceName
              operator: In
              values:
              - book
          topologyKey: kubernetes.io/hostname
  containers:
  - name: nginx
    image: nginx
