version: "3"
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    healthcheck:
      test: curl http://localhost || exit 1
      interval: 5s
      timeout: 10s
      retries: 2
