apiVersion: v1
kind: Service
metadata:
  name: service-nodeport
spec:
  type: NodePort
  selector:
    app: simple
  ports:
    - name: nginx
      port: 80
      targetPort: 80
      nodePort: 30007
    - name: redis
      port: 6379
      targetPort: 6379
      nodePort: 30008
