apiVersion: v1
kind: Pod
metadata:
  name: pod-multi-container
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
    - name: curlpod
      image: radial/busyboxplus:curl
      command:
        - sh
        - -c
        - while true; echo "Hello World"; do sleep 1; done
