apiVersion: v1
kind: Service
metadata:
  name: service-export-two-port
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
